name: Auto Merge to master

on:
  push:
    branches:
      - prueba1

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          echo "machine github.com login actions password ${GH_TOKEN}" > ~/.netrc

      - name: Merge changes into master
        run: |
          git fetch origin master
          git checkout master
          git merge --no-ff --allow-unrelated-histories refs/heads/prueba1
          git push
